### ISSUE TITLE
Feature Request: Add a config option to use chars from a UTF-8 file

### ISSUE THREAD

**Issue by dan200** [vladimirgamalian/fontbm#2]
Hiya, thanks for writing this tool! I've been looking for a cross platform implementation of BMFont.
That said, it's missing possibly the most useful BMFont feature, and i'd like to request it: the "add characters from file" option. This option would take a path to a UTF-8 formatted text file, and include all the characters contained in the file in the font. This is very useful if you have, for example, a file full of Japanese text you wish to display with your program, but you don't want to include all 10000+ characters in the CJK unicode planes in your font images.

**Comment by vladimirgamalian** [comment]
Thanks! I'v added charsFile options just now. But there is a limitation for characters greater than 65536, I'm still working for.

**Comment by vladimirgamalyan** [comment]
Upd: now all the UTF-8 characters (include >= 65536) are supported.
